let a = 10;
document.write("<p>&emsp;&emsp;Result:</p><p>&emsp;&emsp;The value of a is: "+a+"</p><hr>");
++a;
document.write("<p>&emsp;&emsp;The value of ++a is: "+a+"</p><p>&emsp;&emsp;Now the value of a is: "+a+"</p><hr>");
a++;
document.write("<p>&emsp;&emsp;The value of a++ is: "+a+"</p><p>&emsp;&emsp;Now the value of a is: "+a+"</p><hr>");
--a;
document.write("<p>&emsp;&emsp;The value of a++ is: "+a+"</p><p>&emsp;&emsp;Now the value of a is: "+a+"</p><hr>");
a--;
document.write("<p>&emsp;&emsp;The value of a++ is: "+a+"</p><p>&emsp;&emsp;Now the value of a is: "+a+"</p><hr>");